[server]
maxUploadSize = 1000
enableXsrfProtection = false
enableCORS = false

[theme]
primaryColor = "#1a73e8"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f8f9fa"
textColor = "#202124"
font = "sans serif"

[browser]
gatherUsageStats = false